# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html
* Уэс Маккини. Python и анализ данных

In [2]:
import numpy as np

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [361]:
arr = np.random.uniform(0, 20, size=(4, 7))
print(arr)
mmin = np.min(arr)
mmax = np.max(arr)
arr/(mmax-mmin)-mmin/(mmax-mmin)

[[ 6.82126706  4.96618748 11.34759117  2.16280203 10.71973645 15.24693506
  11.47725457]
 [ 6.2738735  19.71159092  5.84909776  9.50903166 12.96604261 16.27539078
   6.745738  ]
 [ 5.85927569 15.7716058   6.63031999  7.67742824  0.86594976 10.16198133
  16.31755181]
 [ 0.05261532  0.33871749 12.83200054 13.12962319 10.7904322  16.55781081
   7.01380218]]


array([[0.34430338, 0.2499404 , 0.57454549, 0.10733961, 0.54260819,
        0.77289479, 0.58114113],
       [0.31645892, 1.        , 0.2948517 , 0.48102284, 0.65687183,
        0.8252096 , 0.34046142],
       [0.29536943, 0.7995834 , 0.33459041, 0.38785403, 0.04137217,
        0.51423666, 0.82735422],
       [0.        , 0.01455326, 0.65005347, 0.66519274, 0.54620429,
        0.83957556, 0.35409713]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [17]:
arr = np.random.randint(0, 10, size=(8, 10))
print(arr)
mmin = np.min(np.sum(arr, axis=1))
#print(mmin, np.sum(arr, axis=1))
print(np.argmin(np.sum(arr, axis=1)))
print(arr[np.argmin(np.sum(arr, axis=1))])

[[9 5 4 6 4 2 1 6 9 5]
 [2 2 2 6 8 1 0 9 1 1]
 [1 1 6 8 4 7 6 4 3 2]
 [8 2 1 0 8 1 9 1 1 3]
 [1 8 8 3 3 7 3 3 1 8]
 [2 9 2 9 3 4 4 3 8 8]
 [9 1 3 3 4 5 1 1 0 5]
 [7 3 7 1 7 6 4 3 6 2]]
1
[2 2 2 6 8 1 0 9 1 1]


3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [399]:
a=np.array([1, 3, 4])
b=np.array([4, 5, 6])
(np.sum((a-b)**2))**0.5

4.123105625617661

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [402]:
a = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
b = np.array([[3, -1], [2, 1]])
c = np.array([[7, 21], [11, 8], [8, 4]])
x = np.linalg.inv(a)@(-c)@np.linalg.inv(b)
x

array([[ 1.00000000e+00,  1.11022302e-15],
       [-2.00000000e+00,  1.00000000e+00],
       [ 3.00000000e+00, -4.00000000e+00]])

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [404]:
arr = np.loadtxt("minutes_n_ingredients.csv", dtype="int32", skiprows=1, delimiter=",")
arr[:5]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]])

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [405]:
print("Среднее ", np.mean(arr[:,1:], axis=0))
print("Минимум ", np.min(arr[:,1:], axis=0))
print("Максимум ", np.max(arr[:,1:], axis=0))
print("Медиана ", np.median(arr[:,1:], axis=0))

Среднее  [2.16010017e+04 9.05528000e+00]
Минимум  [0 1]
Максимум  [2147483647         39]
Медиана  [40.  9.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [406]:
print("Квантиль 0,75 = ", np.quantile(arr[:, 1], q =0.75))
arr[arr[:, 1] <  np.quantile(arr[:, 1], q =0.75)]

Квантиль 0,75 =  65.0


array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [371794,     35,      8],
       [ 43407,     35,      7],
       [370915,      5,      4]])

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [407]:
print("Продолжительность равна 0 у ", np.sum(arr[:, 1] == 0))

Продолжительность равна 0 у  479


In [408]:
arr[arr[:, 1] == 0, 1] = 1
arr

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [498432,     65,     15],
       [370915,      5,      4],
       [ 81993,    140,     14]])

In [409]:
print("Продолжительность равна 0 у ", np.sum(arr[:, 1] == 0))

Продолжительность равна 0 у  0


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [296]:
np.unique(arr, axis = 0).shape[0]

100000

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [297]:
print(np.unique(arr[:, 2], axis = 0).size)
print(np.unique(arr[:, 2], axis = 0))

37
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [298]:
arr1 = arr[arr[:, 2] <= 5] 
arr1

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]])

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [303]:
arr2 = arr[:, 2]/arr[:, 1]
print(np.max(arr2))
arr2

24.0


array([0.26666667, 0.28      , 0.6       , ..., 0.23076923, 0.8       ,
       0.1       ])

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [528]:
np.mean(arr[arr[:,1].argsort()][-100:-1, 2])

6.595959595959596

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [304]:
arr[np.random.choice(arr.shape[0], 10, replace=False), :]

array([[393840,     24,     10],
       [181070,     45,     10],
       [158778,     22,      8],
       [ 52775,     20,     11],
       [ 16576,     55,      7],
       [410364,     45,      8],
       [125701,     70,      7],
       [307986,     50,     11],
       [ 75084,     40,     13],
       [ 49914,     15,      8]])

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [305]:
np.sum(arr[:, 2] < np.mean(arr[:, 2]))/arr.shape[0]*100

58.802

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [334]:
arr3 = arr.copy()
arr3 = np.column_stack([arr3, (arr[:,1] <= 20) & (arr[:,2] <= 5)])
arr3

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,    140,     14,      0]])

13. Выведите процент "простых" рецептов в датасете

In [338]:
np.sum(arr3[:, 3])/arr3.shape[0]*100

9.552

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [524]:
arr = np.loadtxt("minutes_n_ingredients.csv", dtype="int32", skiprows=1, delimiter=",")

In [525]:
leng = min(arr[arr[:,2] < 10].shape[0], arr[arr[:,2] >= 20].shape[0], arr[(arr[:,2] >= 10)&(arr[:,2] < 20)].shape[0])

In [526]:
arr4 = np.zeros((3,leng, 3), dtype = np.int32)
arr4[0, :] = arr[arr[:,2] < 10][:leng]
arr4[1, :] = arr[(arr[:,2] >= 10)&(arr[:,2] < 20)][:leng]
arr4[2, :] = arr[arr[:,2] >= 20][:leng]
arr4

array([[[ 23891,     25,      7],
        [ 94746,     10,      6],
        [ 67660,      5,      6],
        ...,
        [230210,     30,      6],
        [281614,     25,      8],
        [139843,     50,      6]],

       [[127244,     60,     16],
        [157911,     60,     14],
        [280968,     85,     11],
        ...,
        [382527,     55,     12],
        [ 19716,     30,     10],
        [ 37210,     25,     10]],

       [[504666,     65,     20],
        [ 44512,     50,     20],
        [470973,    180,     20],
        ...,
        [188457,    735,     26],
        [ 51720,     30,     22],
        [451245,    390,     21]]])

In [527]:
arr4.shape

(3, 1074, 3)